### ISSUE TITLE
Testing webhook

### ISSUE THREAD

**Issue by pontifex** [affinitylicensing/affinity-api-docs#8]
Hi guys,

I am trying to test Affinity webhook feature as described here [https://github.com/affinitylicensing/affinity-api-docs/blob/master/docs/testing-design-phases.md](url) and simply it does not work. There is no incoming webhook request at all. Absolutely nothing in server logs (it logs all other requests properly) although on web, status of uploaded image is being changed properly. I tried almost each of options there to set in title - no luck. Of course I set up webhook URL here https://stage.affinity-gateway.com/profile/edit and it is correct one. Local server is exposed to the web through ngrok and is accessible from various locations around the world. No idea what do I miss. Any hints?

**Comment by chrishaffinity** [comment]
Hi Lucas,

You're doing everything correctly, I'll let you know when we have a fix.

**Comment by chrishaffinity** [comment]
We've made a change to address this -- can you check whether you're receiving webhook requests now? Thanks.

**Comment by pontifex** [comment]
Hi Chris, you are a man!. It works now. Thank you very much :heart:

**Comment by pontifex** [comment]
Hi, sorry for re-opening, I broke it. :) There is a development phase done, I wanted to move everything to staging server. So I set up my app on staging server and I updated URL here https://stage.affinity-gateway.com/profile/edit to the correct one and... it stopped to work again. Nothing in logs related to webhook, image and status is on https://stage.affinity-gateway.com/designs as expected. Is there any cache on webhook URL value etc? If yes, how many seconds to invalidate? Unfortunately I am unable to listen on original URL any more (the one I had a week ago, which worked cool).

Edit. I tried to set up another ngrok URL for my local instance (just in case it may be staging related issue) and after updating URL on profile edit it still does not work.

**Comment by chrishaffinity** [comment]
Hi Lucas,

Could you email me at chrish@affinitylicensing.com with whatever ngrok URL you want this to post to? Thanks!

**Comment by pontifex** [comment]
Hi Chris,

email sent. Thanks!

**Comment by pontifex** [comment]
There were a merge issue on Affinity side which we found out during few additional tests done together. Fix added by @chrishaffinity Everything works now. Thanks for your help.
